// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5KjBeZW8PtjxpWn8dwHjm3QlmOu8yYTY',
    appId: '1:756323925648:web:6d5fd415ff93887982e215',
    messagingSenderId: '756323925648',
    projectId: 'jarvis-ai-chat',
    authDomain: 'jarvis-ai-chat.firebaseapp.com',
    storageBucket: 'jarvis-ai-chat.firebasestorage.app',
    measurementId: 'G-ETG7NSYC66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5nR5dAaxgCr5Cb5HV3CDIINGZ0o-8-GU',
    appId: '1:756323925648:android:d80f76bd906a28a282e215',
    messagingSenderId: '756323925648',
    projectId: 'jarvis-ai-chat',
    storageBucket: 'jarvis-ai-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0D4qZrhaO-cw6CZA-n7vQZF6px9DrYuc',
    appId: '1:756323925648:ios:a4b41ecddb435f1982e215',
    messagingSenderId: '756323925648',
    projectId: 'jarvis-ai-chat',
    storageBucket: 'jarvis-ai-chat.firebasestorage.app',
    iosBundleId: 'com.example.aichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0D4qZrhaO-cw6CZA-n7vQZF6px9DrYuc',
    appId: '1:756323925648:ios:a4b41ecddb435f1982e215',
    messagingSenderId: '756323925648',
    projectId: 'jarvis-ai-chat',
    storageBucket: 'jarvis-ai-chat.firebasestorage.app',
    iosBundleId: 'com.example.aichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5KjBeZW8PtjxpWn8dwHjm3QlmOu8yYTY',
    appId: '1:756323925648:web:d22dcff960eab3a582e215',
    messagingSenderId: '756323925648',
    projectId: 'jarvis-ai-chat',
    authDomain: 'jarvis-ai-chat.firebaseapp.com',
    storageBucket: 'jarvis-ai-chat.firebasestorage.app',
    measurementId: 'G-XZ13LGH0Q0',
  );
}
